server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/johnlight777/microservices-course-on-youtube-config-store
          search-paths:
           - '*service'



